language: php

php:
  - 5.5

# cache composer downloads so installing is quicker
cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install

  - cp config/config.travis.ini.dist config/config.development.ini

script:
  - cd tests; phpunit
