language: php

php:
  - 5.5
  - 5.4
  - 5.3

# cache composer downloads so installing is quicker
cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install

script:
  - cd tests; phpunit
