application:
  title: OpenCFP
  url: http://localhost
  email: contact@openconf.com
  eventurl: http://localhost
  enddate: Oct. 14th, 2016
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: true

cache:
  enabled: false
  directory: /cache

database:
  host: 127.0.0.1
  database: cfp_travis
  dsn: mysql:dbname=cfp_travis;host=127.0.0.1
  user: root
  password: ""

mail:
  host: localhost
  port: 25
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
